const tg = window.Telegram?.WebApp;
tg?.ready(); tg?.expand();
const state = { products: [], cart: JSON.parse(localStorage.getItem('normwear_cart') || '{}'), category:'Все', query:'' };
const app = document.getElementById('app');
const apiBase = '';
const esc = s => String(s ?? '').replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function money(v){ return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(v)+' ₽'; }
function saveCart(){localStorage.setItem('normwear_cart',JSON.stringify(state.cart));}
function cartCount(){return Object.values(state.cart).reduce((a,b)=>a+b.qty,0)}
function productCard(p){return `<article class="card" data-id="${p.id}"><img loading="lazy" src="${p.media?.[0] || ''}" onerror="this.style.display='none'"><div class="meta"><div class="title">${esc(p.title)}</div><div class="price">${money(p.price)}</div><button class="buy" onclick="addToCart(${p.id})">В корзину</button></div></article>`}
function render(){
 const cats=['Все',...new Set(state.products.map(p=>p.category).filter(Boolean))];
 const filtered=state.products.filter(p=>(state.category==='Все'||p.category===state.category)&&(!state.query||p.title.toLowerCase().includes(state.query.toLowerCase())));
 app.innerHTML=`<div class="app"><header><div class="brand">NORMWEAR</div><div class="search"><span>⌕</span><input id="q" placeholder="Поиск товаров" value="${esc(state.query)}"></div></header><section class="hero"><small>NEW DROP</small><h1>Новая коллекция</h1><p>Актуальные модели с заказом прямо внутри Telegram.</p></section><div class="chips">${cats.map(c=>`<button class="${c===state.category?'active':''}" onclick="setCategory('${esc(c)}')">${esc(c)}</button>`).join('')}</div><main>${filtered.length?filtered.map(productCard).join(''):'<div class="empty">Ничего не найдено</div>'}</main><nav><span onclick="scrollTo(0,0)">⌂<small>Главная</small></span><span>♡<small>Избранное</small></span><span onclick="showCart()">🛒<small>Корзина ${cartCount()?`(${cartCount()})`:''}</small></span><span>◉<small>Профиль</small></span></nav></div>`;
 document.getElementById('q').oninput=e=>{state.query=e.target.value; render()}
}
window.addToCart=id=>{ state.cart[id]=state.cart[id]||{qty:0}; state.cart[id].qty++; saveCart(); render(); tg?.HapticFeedback?.impactOccurred('light'); }
window.setCategory=c=>{state.category=c;render()}
window.showCart=()=>{const items=Object.entries(state.cart).map(([id,x])=>{const p=state.products.find(p=>p.id==id);return p?{...x,p}:null}).filter(Boolean);const total=items.reduce((s,x)=>s+x.p.price*x.qty,0);const u=tg?.initDataUnsafe?.user;app.innerHTML=`<div class="app"><header><button class="back" onclick="render()">← Назад</button><div class="brand">КОРЗИНА</div></header><main class="cart">${items.length?items.map(x=>`<div class="cartrow"><b>${esc(x.p.title)}</b><span>${x.qty} × ${money(x.p.price)}</span></div>`).join(''):'<div class="empty">Корзина пуста</div>'}</main><div class="checkout"><div>Итого: <b>${money(total)}</b></div><div class="form" style="display:flex;flex-direction:column;gap:8px;margin:12px 0"><input id="c_name" placeholder="Имя" value="${esc(u?.first_name||'')}"><input id="c_phone" placeholder="Телефон +7..." inputmode="tel"><input id="c_city" placeholder="Город"><input id="c_address" placeholder="Адрес (улица, дом, кв)"><input id="c_comment" placeholder="Комментарий (необязательно)"></div><button class="buy checkoutbtn" onclick="checkout()">Оформить заказ</button></div></div>`}
window.checkout=async()=>{const items=Object.entries(state.cart);if(!items.length)return; if(!tg?.initData){alert('Откройте магазин из Telegram');return;} const get=(id)=>document.getElementById(id)?.value?.trim()||''; const name=get('c_name'), phone=get('c_phone'), city=get('c_city'), address=get('c_address'), comment=get('c_comment'); if(!name||!phone||!city||!address){alert('Заполните имя, телефон, город и адрес');return;} const lines=items.map(([id,x])=>({product_id:Number(id),quantity:x.qty,size:null})); const payload={lines,name,phone,city,address,comment:comment||null,payment_method:'sbp'}; const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg.initData},body:JSON.stringify(payload)}); const d=await r.json(); if(!r.ok){alert(d.detail||'Ошибка');return;} state.cart={};saveCart();app.innerHTML=`<div class="app success"><div class="mark">✓</div><h1>Заказ #${d.order_id} принят</h1><p>Стоимость доставки менеджер рассчитает отдельно и сообщит итоговую сумму.</p><button class="buy" onclick="render()">Вернуться в каталог</button></div>`}
(async()=>{try{const r=await fetch('/api/products?limit=50');state.products=await r.json()}catch(e){state.products=[]}render()})();
